# Hybrid CV Pipeline for Bacterial Segmentation & Growth Analysis

## Overview

A Python pipeline combining classical computer vision with deep learning for analyzing bacterial time-lapse microscopy. Designed for _Mycobacterium smegmatis_ NCTC 8159 antibiotic susceptibility testing. The goal is to enhance segmentation stability and extract motion features for early detection of antibiotic response.

This pipeline refines Omnipose segmentation masks using Gaussian smoothing, Sobel edge detection, and optional watershed refinement. It incorporates a continuous memory mask for temporal stability and employs Lucas-Kanade optical flow to extract motion features indicative of early antibiotic response. It compares a baseline area-based growth analysis with a hybrid method that includes motion features.

Note that this is still a work in progress as we are still getting erroneous results when we incorporate watershed with motion features. In some frames and positions, the watershed seems to make things worse rather than better. Watershed is therefore an optional flag in this implementation. Moreover, the motion features are yet to be refined but as of now, we get a shorter time-to-detection using motion features compared to area-based growth alone.

## Quick Start

### 1. Installation

Core packages and optional pytest for testing:

```bash
pip install numpy scipy scikit-image opencv-python matplotlib pandas
pip install pytest
```

### 2. Verify packages are working (generated by Copilot)

```bash
python test_installation.py
or
pytest test_installation.py -v
```

### 3. Configure Paths

Edit `config.py`:

```python
BASE_DIR = "./data"  # Update to your data location
```

### 4. Run Examples

```bash
python example_usage.py
```

The script will prompt you to select a position (101-110 for REF, 201-220 for RIF10).

## Project Structure

```
rmeth/
├── config.py                  # Configuration (UPDATE THIS!)
├── hybrid_pipeline.py         # Main pipeline implementation
├── analysis_notebook.py       # Full analysis workflow
├── example_usage.py          # Interactive examples
├── parameter_tuner.py        # Parameter optimization tool
├── test_installation.py      # Test suite (30 tests)
└── data/                     # Your data goes here
    ├── REF_raw_data101_110/
    │   └── Pos101-110/aphase/*.tiff
    ├── REF_masks101_110/
    │   └── Pos101-110/PreprocessedPhaseMasks/MASK_*.tif
    ├── RIF10_raw_data201_210/
    │   └── Pos201-220/aphase/*.tiff
    └── RIF10_masks201_210/
        └── Pos201-220/PreprocessedPhaseMasks/MASK_*.tif
```

## Data Structure

**Expected folder layout:**

```
data/
├── REF_raw_data101_110/      # Reference (untreated)
│   ├── Pos101/aphase/img_*.tiff
│   ├── Pos102/aphase/img_*.tiff
│   └── ... (Pos103-110)
├── REF_masks101_110/         # Omnipose masks
│   ├── Pos101/PreprocessedPhaseMasks/MASK_*.tif
│   └── ... (Pos102-110)
├── RIF10_raw_data201_210/    # Treatment (Rifampicin 10mg/L)
│   └── Pos201-220/aphase/img_*.tiff
└── RIF10_masks201_210/
    └── Pos201-220/PreprocessedPhaseMasks/MASK_*.tif
```

## Usage

### Basic Example

```python
from hybrid_pipeline import (
    HybridSegmentationPipeline,
    OpticalFlowAnalyzer,
    GrowthAnalyzer
)
import config

# Initialize components
seg_pipeline = HybridSegmentationPipeline(
    gaussian_sigma=config.GAUSSIAN_SIGMA,
    use_watershed=config.USE_WATERSHED
)
flow_analyzer = OpticalFlowAnalyzer()
growth_analyzer = GrowthAnalyzer()

# Process frames
refined_masks, edges = seg_pipeline.process_sequence(
    frames, omnipose_masks, use_memory=True
)

# Analyze growth
areas = growth_analyzer.compute_area_growth(refined_masks)
flow_features = flow_analyzer.extract_sequence_features(frames, refined_masks)
```

### Interactive Frame Viewer

```bash
python sample_position.py
# Navigate desired position (from 101-110 for REF, 201-220 for RIF10 => from console input) frames with slider or arrow keys
# View segmentation comparison in real-time
```

### Parameter Tuning

```bash
python parameter_tuner.py
# Adjust Gaussian sigma, Sobel kernel, watershed distance
# See results in real-time
```

### Full Analysis

```bash
python analysis.py
# Processes all positions
# Generates comprehensive comparison plots
# Calculates time-to-detection metrics
```

## Configuration

All parameters are centralized in `config.py`:

## Output

Output files are saved in `results/full_hybrid_output` and `results/sample_analysis_output` for full and sample analyses, respectively.

- `baseline_area_growth.png` - Baseline method
- `hybrid_area_growth.png` - Hybrid method
- `hybrid_motion_growth.png` - Motion features
- `comprehensive_comparison.png` - 4-panel summary
- `analysis_summary.pickle` - Complete results

## Pipeline Components

### 1. HybridSegmentationPipeline

- Gaussian blur preprocessing
- Sobel edge detection
- Optional watershed refinement
- Continuous memory mask for temporal stability

### 2. OpticalFlowAnalyzer

- Lucas-Kanade optical flow
- Motion magnitude and directional consistency
- Frame-to-frame growth quantification

### 3. GrowthAnalyzer

- Area-based growth curves
- Rolling window growth rates
- Motion-based growth metrics
- Time-to-detection calculation

## Testing

Run the test suite:

```bash
python test_installation.py
```

**Test coverage:**

- Dependencies (6 tests)
- Pipeline imports (4 tests)
- Instantiation (4 tests)
- Preprocessing (3 tests)
- Watershed (2 tests)
- Memory mask (2 tests)
- Optical flow (3 tests)
- Growth analysis (3 tests)
- Configuration (3 tests)
